lbryio/lbcd

- fees/README.md
- fees/cmd/dumpfeedb/dumpfeedb.go
- fees/doc.go
- fees/estimator.go
- fees/log.go
- log.go
- mempool/mempool.go
- netsync/interface.go
- netsync/manager.go
- rpcserver.go
- server.go
Closing #17 
Ported the fee estimator from DCRD, whose implementation is based on bitcoin core v0.14.
Lbrycrd (v0.17) includes the some improvement from bitcoin v0.15.
Test fixtures can't be reused, we need to manually / visually test against mainnet transaction flow.
> Port `estimatesmartfee` from dcrd

- wire/msgblock.go
- wire/msgblock_test.go
- wire/msgmerkleblock_test.go
- wire/msgtx_test.go
This variable seems redundant to the blockchain.MaxBlockBaseSize to make the `wire` and `blockchain` self-contained.
We've updated the `blockchain.MaxBlockBaseSize` to 8MB for LBRY, but missed this one?
> Increase wire.MaxBlockPayload to 8MB

- btcjson/chainsvrresults.go
- mempool/mempool.go
- rpcserver.go
- rpcserverhelp.go
Closing #22 
Mocking the missing fields s the [mempool](https://github.com/mempool/mempool) intgration can move ahead to discover other issues, if any.
> wip: update getrawmempool

- rpcclient/infrastructure.go
Update rpcclient, which is a dependency of lbryio/lbcwallet#5
> rpcclient: support SkipVerify of TLS certificate.

- .goreleaser.yml
This is the only missing step to make the compiled binaries deterministic.
> [lbry] ci: GoReleaser zero out buildid for reproducible builds

- lbcd.go
Unbundled from PR https://github.com/lbryio/lbcd/pull/43
See that for usage/testing. (TODO)
The default (10) only lets heap grow 10% before triggering GC. Running with (for example) "GOGC=100" will reduce CPU usage while heap is allowed to fluctuate more.
> Allow environment var GOGC=<percent> to override hard-coded SetGCPercent(10)

- config.go
- doc.go
- lbcd.go
- sample-lbcd.conf
Unbundled from PR https://github.com/lbryio/lbcd/pull/43
See that for usage/testing.
> Add --memprofile option. Add memprofile to sample config.

- claimtrie/change/change.go
- claimtrie/node/noderepo/pebble.go
Unbundled from PR: https://github.com/lbryio/lbcd/pull/43
See that for usage/testing.
Based on work by @BrannonKing in mem_pressure_try_2 and reduce_memory_pressure.
The stuff in 92d8b5f20ee81c97aa9f6fab434251f573819f10 is something that seems unsafe which I found while debugging. The database was being corrupted, and I was seeing crashes in Change.Unmarshal() trying to read bytes that weren't there.
Eventually I figured out the problem was in the merger, and submitted 728ddc4dfa4533d5155a3c4c831d604e29d74537
> Pebble pooled merger

- claimtrie/claimtrie.go
Default value of GOMAXPROCS is NumCPU(), so ordinary behavior does not change.
However, this allows tuning the number of threads used for claimtrie rebuild.
> Allow environment var GOMAXPROCS=<N> to override NumCPU().

- config.go
- doc.go
> [lbry] config: allow non-localhost connections with TLS disabled

- claimtrie/claimtrie.go
Print out if RramTrie was fully rebuilt during `claimtrie.ResetHeight()` to help triage the issue #71
> [lbry] claimtrie: more verbose error message in ResetHeight

- btcjson/chainsvrresults.go
- mempool/mempool.go
- mempool/mempool_test.go
- mempool/memusage.go
- rpcserver.go
- rpcserverhelp.go
- server.go
Fixes https://github.com/lbryio/lbcd/issues/60
Field "loaded" only makes sense if the Mempool is being saved/loaded on restart. I don't see that happening.
Field "maxmempool" would need more configuration infrastructure, and could be supported if that were added.
The "usage" (memory) and "unbroadcastcount" were my attempt to mimic what's done in C++ bitcoin (https://github.com/bitcoin/bitcoin).
Manual test, showing rollover back to near 0 size, apparently on new block acceptance.
```
Mac-mini lbcd % ./lbcctl --rpcuser=xxx --rpcpass=yyy getmempoolinfo
{
"size": 267,
"bytes": 256195,
"usage": 347789,
"total_fee": 0.21047744,
"mempoolminfee": 0.00001,
"minrelaytxfee": 0.00001,
"unbroadcastcount": 0
}
Mac-mini lbcd % ./lbcctl --rpcuser=xxx --rpcpass=yyy getmempoolinfo
{
"size": 3,
"bytes": …
```
> Rpc mempool: Support more fields in getmempoolinfo result.

- rpcclient/examples/lbcdblocknotify/main.go
> lbcdblocknotify: support --run to execute custom command

- rpcserver.go
According to the BIP0009, all active softfork deployment should
be included in the rules.
We add the '!' to indicate the enforcement if the template has
any segwit transactions in it. Otherwise, plain `segwit` is fine.
> mining: include 'segwit' rule when no segwit txns in GBT

- blockchain/chain.go
- btcjson/walletsvrcmds.go
- btcjson/walletsvrresults.go
- rpcclient/wallet.go
- rpcserver.go
> rpc: make getblock return orphans

- mempool/policy.go
- mempool/policy_test.go
An output is considered dust if the cost to the network to spend the
coins is more than 1/3 of the minimum free transaction relay fee, which
has a default rate of 1000 satoshis/kb
bitcoind refactored dust threshold calculation, which removed the
multiply factor of 3 from the code, but increased the DUST_RELAY_TX_FEE
from 1000 to 3000 (satoshi/kb).
lbrycrd adopted the refactored code but also kept the rate to
1000 dewies/kB, which means:
An output is considered dust if the cost to the network to spend the
coins is more than the minimum free transaction relay fee.
This commit updates lbcd to align the policy.
> policy: relax dust thrashold to 1000 dewies/kB, which aligns to lbrycrd

- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- rpcclient/rawtransactions.go
- rpcserver.go
- rpcserverhelp.go
> rpc: support hex data output for createrawtransaction

- rpcserver.go
Fix #96 
Although the BIPs specify that `coinbasetxn` and `coinbasevalue` are mutually exclusive, both the latest bitcoind (22.0.0) and lbrycrd (0.17.3) returns .coinbasevalue regardless if 'coinbasetxn' is specified in the capabilities.
We'll make lbcd behave the same for compatibility.
> mining: always returns .coinbasevalue in getblocktemplate

- btcjson/walletsvrcmds.go
- btcjson/walletsvrcmds_test.go
- btcjson/walletsvrresults.go
- btcjson/walletsvrwscmds.go
- btcjson/walletsvrwscmds_test.go
- rpcclient/wallet.go
Most of the updates add optional arguments with default values.
> rpc: update rpc cmd requests to support multi-account

- rpcclient/infrastructure.go
in the case where you're e.g. trying to connect to an invalid address, the err vars in `handleSendPostMessage()` were being shadowed inside the for loop. if `c.httpClient.Do()` returned an error, that error never got returned upstream. then `ioutil.ReadAll(httpResponse.Body)` would get a nil pointer dereference. 
this fixes that case.
> error properly when lbcd fails to connect in HTTP POST mode
